resourcestring                                     {deutsch}

  manual='Owon HDS242 User Manual_de.PDF';
{$IFDEF LINUX}
  DownURL='/downloads/owon_oszi.tar.gz';
{$ELSE}
    DownURL='/downloads/owon_oszi.zip';
{$ENDIF}

rsAction='Auswerten gespeicherter Anzeigen vom';
rsTime='Zeitbasis';
rsVolt='Spannung';
rsDelta='X-Delta';
openCSVfile='CSV-Datei öffnen...';
openBMPfile='Screenshot öffnen...';
capClose='&Beenden';
hntClose='Programm beenden.';
capImage='&Screenshot';
hntImage='Vom HDS242 aufgenommenen Screenshot anzeigen.';
capCSVfile='&CSV-Datei';
hntCSVfile='Vom HDS242 als CSV-Datei gespeicherte Waveform anzeigen.';
capFile='&Datei';
capInfo='&Info';
capAbout='&Über...';
capManual='&HDS242 Handbuch';
capTeiler='Teiler';
hntTeiler='Teilerfaktor des Tastkopfes.';
capChannel='Kanal ';
hntChannel='Öffne Datei vom HDS242 oder schiebe sie per Drag&Drop auf das Programmfenster.';
capSaveScreen='&Anzeige speichern...';
capSaveDlg='Anzeige in PNG-Datei speichern...';
hntSaveScreen='Anzeige als Bild in PNG-Datei speichern.';
capKursor='Kursor (+ Shift)';
hntKursor='Kursor mit linker Maustaste + Shift-Taste anzeigen';
capDownload='Download Update';
capHomepage='Homepage';


